Feautre/test option
diegohaz/webpack-blocks-split-vendor pull request #25
Opened 2018-02-21 20:10 UTC by dmitmel

See #24

2018-02-22 12:31 UTC, diegohaz requested changes
Thank you so much, @dmitmel. I've made some comments. Let's try to keep code quality.

2018-02-22 12:31 UTC, diegohaz commented on .eslintrc
> +    "no-param-reassign": 0,
Let's try to keep methods pure and not mutate arguments.

2018-02-22 12:31 UTC, diegohaz commented on src/index.js
> +  if (options.test == null) options.test = /\.js$/
Don't mutate arguments and let's not ignore coverage. It's there for a reason, I can write tests later if you can't.

2018-03-03 15:57 UTC, merged

2018-03-03 15:57 UTC, diegohaz commented
Thank you, @dmitmel.

2018-03-07 14:01 UTC, dmitmel commented
@diegohaz Would you like to create a new release with changes made in this PR?